[build]
  publish = "."
  command = ""

[dev]
  framework = "#static"

[[headers]]
  for = "/script.js"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/styles.css"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/seo.css"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    cache-control = "public, max-age=0, must-revalidate"
